### ISSUE TITLE
Gerbv scales down when I export to SVG

### ISSUE THREAD

**Issue by Anakievs** [gerbv/gerbv#231]
I have this example gerber file with two "circles". The distance between them is 2.54mm. If I export to PDF and then open in Inkscape the distance is still 2.54mm. But if I export to SVG the distance is scaled down to 1.91mm. Everything is scaled down and you can't realize it until you measure it or print it. The same happens with the Print option.

This happens in Arch Linux with the latest version (from AUR) 2.10.0 but also with 2.9.5. I had to use Windows 7 with this version gerbv-win-static_20160713 to properly export my files.
[samples.zip](https://github.com/gerbv/gerbv/files/13619507/samples.zip)

The bug is present in version gerbv-2.7.0. This is the oldest version available to download from archive.archlinux.org so I can't test earlier versions.

**Comment by Anakiev2** [comment]
It exports properly in Debian 12 with version 2.9.6-1. But still wrong in Arch. Any ideas?

**Comment by Anakiev2** [comment]
I did a quick comparison between the svg files form Arch and Debian and on the second line the Arch file misses 'pt' in 'width' and 'height' fields.
```sh
Arch file
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="9" height="1" viewBox="0 0 9 1">
Debian file
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="9pt" height="1pt" viewBox="0 0 9 1" version="1.1">
```
When I add 'pt' to the 'wrong' file it opens correctly.
[comparison.zip](https://github.com/gerbv/gerbv/files/15027874/comparison.zip)

**Comment by eyal0** [comment]
Maybe the two are not from the same version of gerbv? Why would one have it and one not?

Or maybe it is using an SVG library that is different between the two. Does gerbv use librsvg? Check what versions you have installed?

**Comment by Anakiev2** [comment]
I've tried with different versions on Arch. It was the same. Looking at the PKGBUILD it doesn't look to use shared libraries.
```sh
depends=('gtk2' 'dconf')
optdepends=('cairo: for better graphics')
```
Here is a list of all versions I've tried:
```sh
gerbv (2.9.5-1)
gerbv (2.10.0-1)
gerbv (2.8.1-2)
gerbv (2.7.0-2)
gerbv (2.7.0-1)
```

**Comment by Anakiev2** [comment]
Here is some output from ldd.
Arch:
```sh
linux-vdso.so.1 (0x00007ffd56596000)
libgerbv.so.1 => /usr/lib/libgerbv.so.1 (0x000072624025d000)
libgtk-x11-2.0.so.0 => /usr/lib/libgtk-x11-2.0.so.0 (0x000072623fc00000)
libgdk-x11-2.0.so.0 => /usr/lib/libgdk-x11-2.0.so.0 (0x000072624019e000)
libgdk_pixbuf-2.0.so.0 => /usr/lib/libgdk_pixbuf-2.0.so.0 (0x0000726240159000)
libgio-2.0.so.0 => /usr/lib/libgio-2.0.so.0 (0x000072623fa33000)
libgobject-2.0.so.0 => /usr/lib/libgobject-2.0.so.0 (0x00007262400f9000)
libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x000072623f8e6000)
libcairo.so.2 => /usr/lib/libcairo.so.2 (0x000072623f7b3000)
libm.so.6 => /usr/lib/libm.so.6 (0x000072623f6c7000)
libc.so.6 => /usr/lib/libc.so.6 (0x000072623f4e5000)
libpangocairo-1.0.so.0 => /usr/lib/libpangocairo-1.0.so.0 (0x00007262400e7000)
libatk-1.0.so.0 => /usr/lib/libatk-1.0.so.0 (0x00007262400c0000)
libpangoft2-1.0.so.0 => /usr/lib/libpangoft2-1.0.so.0 (0x00007262400a5000)
libpango-1.0.so.0 => /usr/lib/libpango-1.0.so.0 (0x000072623f47f000)
libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x000072623f370000)
libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x000072623f320000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x000072623f252000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000072623ee00000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000072624007e000)
libgmodule-2.0.so.0 => /usr/lib/libgmodule-2.0.so.0 (0x0000726240077000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x000072623f114000)
libXfixes.so.3 => /usr/lib/libXfixes.so.3 (0x000072623f10c000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x000072623f0ff000)
libXinerama.so.1 => /usr/lib/libXinerama.so.1 (0x000072623f0fa000)
libXi.so.6 => /usr/lib/libXi.so.6 (0x000072623f0e6000)
libXrandr.so.2 => /usr/lib/libXrandr.so.2 (0x000072623f0d9000)
libXcursor.so.1 => /usr/lib/libXcursor.so.1 (0x000072623f0cd000)
libXcomposite.so.1 => /usr/lib/libXcomposite.so.1 (0x000072623f0c8000)
libXdamage.so.1 => /usr/lib/libXdamage.so.1 (0x000072623f0c3000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x000072623f0ae000)
libpng16.so.16 => /usr/lib/libpng16.so.16 (0x000072623edc6000)
libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x000072623ed29000)
libtiff.so.6 => /usr/lib/libtiff.so.6 (0x000072623ec9d000)
libz.so.1 => /usr/lib/libz.so.1 (0x000072623f094000)
libmount.so.1 => /usr/lib/libmount.so.1 (0x000072623ec4d000)
libffi.so.8 => /usr/lib/libffi.so.8 (0x000072623f087000)
libpcre2-8.so.0 => /usr/lib/libpcre2-8.so.0 (0x000072623ebaf000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x000072623eb84000)
libxcb-render.so.0 => /usr/lib/libxcb-render.so.0 (0x000072623eb75000)
libxcb-shm.so.0 => /usr/lib/libxcb-shm.so.0 (0x000072623f080000)
libpixman-1.so.0 => /usr/lib/libpixman-1.so.0 (0x000072623eacb000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000726240301000)
libfribidi.so.0 => /usr/lib/libfribidi.so.0 (0x000072623eaab000)
libthai.so.0 => /usr/lib/libthai.so.0 (0x000072623eaa0000)
libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x000072623ea7d000)
libexpat.so.1 => /usr/lib/libexpat.so.1 (0x000072623ea54000)
libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x000072623ea41000)
libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x000072623ea32000)
libzstd.so.1 => /usr/lib/libzstd.so.1 (0x000072623e95f000)
liblzma.so.5 => /usr/lib/liblzma.so.5 (0x000072623e92c000)
libjbig.so.2.1 => /usr/lib/libjbig.so.2.1 (0x000072623e91f000)
libblkid.so.1 => /usr/lib/libblkid.so.1 (0x000072623e8e6000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x000072623e8e1000)
libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x000072623e8d9000)
libdatrie.so.1 => /usr/lib/libdatrie.so.1 (0x000072623e8d0000)
libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x000072623e8ad000)
```

Debian:
```sh
linux-vdso.so.1 (0x00007fffacb49000)
libgerbv.so.1 => /lib/x86_64-linux-gnu/libgerbv.so.1 (0x00007ffa2ee88000)
libgtk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 (0x00007ffa2ea00000)
libgdk-x11-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0 (0x00007ffa2e944000)
libgdk_pixbuf-2.0.so.0 => /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007ffa2e916000)
libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007ffa2e738000)
libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007ffa2e6d9000)
libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ffa2e5a1000)
libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007ffa2e47d000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffa2e39e000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffa2e1bd000)
libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007ffa2ee80000)
libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007ffa2ee6d000)
libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007ffa2e07b000)
libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007ffa2ee65000)
libatk-1.0.so.0 => /lib/x86_64-linux-gnu/libatk-1.0.so.0 (0x00007ffa2e052000)
libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007ffa2e039000)
libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007ffa2dfd0000)
libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007ffa2df85000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffa2ee5e000)
libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007ffa2df78000)
libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007ffa2df73000)
libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007ffa2df5f000)
libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007ffa2df50000)
libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007ffa2df43000)
libXcomposite.so.1 => /lib/x86_64-linux-gnu/libXcomposite.so.1 (0x00007ffa2df3e000)
libXdamage.so.1 => /lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007ffa2df39000)
libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007ffa2df24000)
libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007ffa2deec000)
libjpeg.so.62 => /lib/x86_64-linux-gnu/libjpeg.so.62 (0x00007ffa2de59000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffa2de3a000)
libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007ffa2ddd7000)
libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007ffa2dda9000)
libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007ffa2dd9d000)
libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007ffa2dd01000)
libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007ffa2dc56000)
libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007ffa2db8b000)
libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007ffa2db86000)
libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007ffa2db5c000)
libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007ffa2db4e000)
/lib64/ld-linux-x86-64.so.2 (0x00007ffa2ef11000)
libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007ffa2da48000)
libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007ffa2da2c000)
libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007ffa2da21000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ffa2d9f6000)
libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007ffa2d99d000)
libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007ffa2d990000)
libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007ffa2d98b000)
libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007ffa2d600000)
libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007ffa2d95f000)
libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007ffa2d953000)
libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007ffa2d930000)
libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007ffa2d91a000)
libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007ffa2d90d000)
```

**Comment by eyal0** [comment]
The SVG is exported using the cairo library, I think.  There is no mention of `xmlns` in the code which leads me to believe that it's the library generating that string, not `gerbv`.  So I'm not sure how to fix it...

**Comment by Anakiev2** [comment]
You are right.
I've made Arch live ISO years ago. When I test the exact same version of gerbv with the ISO it produces the same file as Debian. But the current version of Arch creates the bad one.

**Comment by PingPongun** [comment]
It looks like problem is caused by `cairo` update (similar issue in inkscape: https://gitlab.com/inkscape/inkscape/-/issues/3375) (arch/nix/void all have cairo 2.18, but debian-bookworm is still at 2.16, I'd encoutered same problem on debian-testing which also has cairo 2.18)

**Comment by PingPongun** [comment]
#240 should fix this

**Comment by Anakiev2** [comment]
@PingPongun Thanks it's fixed. But to compile I had to change surface to cSurface as @spe-ciellt suggested.

**Comment by Anakiev2** [comment]
@PingPongun Actually it's not completely fixed. When I "Print" to SVG it's still wrong.

**Comment by PingPongun** [comment]
@Anakiev2 I've updated PR, so that it should now also work with `File>>Print`

**Comment by Anakiev2** [comment]
It works now. Thank you!
